CREATE TABLE USUARIO (
	id_usuario NUMBER(10) NOT NULL,
	usuario VARCHAR2(10) NOT NULL,
	senha VARCHAR2(10) NOT NULL,
	identificador CHAR(1) NOT NULL,
	PRIMARY KEY(id_usuario)
);

CREATE TABLE COLABORADOR (
	id_colaborador NUMBER(10) NOT NULL,
	id_usuario NUMBER(10) NOT NULL,
	nome VARCHAR2(100) NOT NULL,
	cpf VARCHAR2(11) UNIQUE NOT NULL,
	PRIMARY KEY(id_colaborador),
	CONSTRAINT FK_USUARIO FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario)
);

CREATE TABLE CAMINHAO (
	id_caminhao NUMBER(10) NOT NULL,
	id_colaborador NUMBER(10) NOT NULL,
	nome VARCHAR2(100) NOT NULL,
	placa VARCHAR2(10) UNIQUE  NOT NULL,
	PRIMARY KEY(id_caminhao),
	CONSTRAINT FK_COLABORADOR FOREIGN KEY (id_colaborador) REFERENCES COLABORADOR(id_colaborador)
);

CREATE TABLE MOTORISTA (
	id_motorista NUMBER(10) NOT NULL,
	id_usuario NUMBER(10) NOT NULL,
	nome VARCHAR2(100) NOT NULL,
	cnh VARCHAR2(11) UNIQUE NOT NULL,
	PRIMARY KEY(id_motorista),
	CONSTRAINT FK_USUARIO_MOTORISTA FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario)
);

CREATE SEQUENCE seq_usuario
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;


CREATE SEQUENCE seq_colaborador
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;


CREATE SEQUENCE seq_caminhao
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 

CREATE SEQUENCE seq_motorista
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;