CREATE TABLE COLABORADOR (
id_colaborador NUMBER NOT NULL,
nome VARCHAR2(100) NOT NULL,
cpf VARCHAR2(11) UNIQUE NOT NULL,
usuario VARCHAR2(100)UNIQUE NOT NULL,
senha VARCHAR2(100) NOT NULL,
PRIMARY KEY(id_colaborador)
);

CREATE TABLE CAMINHAO(
id_caminhao NUMBER NOT NULL,
placa VARCHAR2(10) UNIQUE NOT NULL,
modelo VARCHAR2(100) NOT NULL,
gasolina NUMBER NOT NULL,
emViagem NUMBER(1), -- se FOR 1 em viagem se FOR 2 ele esta parado
PRIMARY KEY(id_caminhao)
);

-- esquecemos de adicionar a coluna FK id_colaborador 
ALTER TABLE CAMINHAO 
ADD id_colaborador NUMBER NOT NULL;
-- adicionamos a FK atraves dos comandos a baixo
ALTER TABLE CAMINHAO
ADD CONSTRAINT FK_COLABORADOR
  FOREIGN KEY (id_colaborador)
  REFERENCES COLABORADOR(id_colaborador);
  
CREATE TABLE ROTA(
id_rota NUMBER NOT NULL,
id_colaborador NUMBER NOT NULL,
descricao VARCHAR(200),
localPartida VARCHAR(200) NOT NULL,
localDestino VARCHAR(200) NOT NULL,
PRIMARY KEY(id_rota),
CONSTRAINT FK_COLABORADOR_ROTA FOREIGN KEY (id_colaborador) REFERENCES COLABORADOR(id_colaborador)
);

CREATE TABLE POSTO(
id_posto NUMBER NOT NULL,
id_colaborador NUMBER NOT NULL,
nomePosto VARCHAR(200) NOT NULL,
valorCombustivel NUMBER NOT NULL,
PRIMARY KEY(id_posto),
CONSTRAINT FK_COLABORADOR_POSTO FOREIGN KEY (id_colaborador) REFERENCES COLABORADOR(id_colaborador)
);

CREATE TABLE MOTORISTA(
id_motorista NUMBER NOT NULL,
nome VARCHAR2(10) NOT NULL,
cnh VARCHAR2(11) UNIQUE NOT NULL,
usuario VARCHAR2(100) NOT NULL,
senha VARCHAR2(100) NOT NULL,
PRIMARY KEY(id_motorista)
);

CREATE TABLE VIAGEM (
id_viagem NUMBER NOT NULL,
id_caminhao NUMBER NOT NULL,
id_rota NUMBER NOT NULL,
id_motorista NUMBER NOT NULL,
destino VARCHAR2(100) NOT NULL,
distancia NUMBER NOT NULL,
PRIMARY KEY(id_viagem),
CONSTRAINT FK_VIAGEM_MOTORISTA FOREIGN KEY (id_motorista) REFERENCES MOTORISTA(id_motorista),
CONSTRAINT FK_VIAGEM_CAMINHAO FOREIGN KEY (id_caminhao) REFERENCES CAMINHAO(id_caminhao),
CONSTRAINT FK_VIAGEM_ROTA FOREIGN KEY (id_rota) REFERENCES ROTA(id_rota) 
);

CREATE SEQUENCE seq_colaborador
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE seq_caminhao
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE seq_rota
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE seq_motorista
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE seq_viagem
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
